### ISSUE TITLE
Bluebuild Compatability

### ISSUE THREAD

**Issue by Ranakastrasz** [Nexela/PickerExtended#41]
https://mods.factorio.com/mods/Mylon/Bluebuild/discussion/14290

For some reason, with both mods installed, unless I set "Reach Distance" to 6, instead of the default of 30 (Which is not a "Minor" increase) deconstruction only sort of pretends to work. It works on some entities, and not others. I have no idea why exactly.

**Comment by Nexela** [comment]
Compared to long reach's 10000  30 is pretty minor :)

The problem is with bluebuild and any kind of reach
limit = 40 means it will stop looking after 40 entities, these could be entities already marked.  Nanobots handles this by having a higher (or no limit) and limiting by breaking out of the loop after it queues up x amount.
